import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Klasör yapısından otomatik üretiliyor: docs/postgres/*, docs/mongodb/*
// Sıralama her klasördeki _category_.json + dosyaların sidebar_position alanıyla kontrol edilir.
const sidebars: SidebarsConfig = {
  schemaSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
